name: coverage
on:
  push: 
    paths: 
      - '!README.md'
      - '**.js'
    branches: [main, test]
  pull_request:
    type: [opened, reopened, synchronize]
    paths: 
      - '!README.md'
      - '**.js'
    branches: 
      - 'main'
  workflow_dispatch:

jobs: 
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Set Permission for NPX and Jest
        run: |
          sudo chmod +x /usr/local/bin/npx
          sudo chmod +x $(npm bin)/jest
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          threshold: 80
          skip-step: install
