name: coverage
on:
  push:
    paths:
      - '!README.md'
      - '**.js'
    branches: [main, test]
  pull_request:
    type: [opened, reopened, synchronize]
    paths:
      - '!README.md'
      - '**.js'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  Coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Install Jest globally
        run: npm install -g jest
      - name: Check Jest path
        run: which jest
      - name: Check Jest permissions
        run: ls -l $(which jest)
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test
      #     github-token: ${{ secrets.SECRET_TOKEN }}
      #     threshold: 80
      #     skip-step: install
